server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: c:/promtail/positions.yaml
clients:
  - url: http://localhost:3100/loki/api/v1/push
scrape_configs:
- job_name: windows_event_camstar
  windows_events:
    use_incoming_timestamp: false
    bookmark_path: "./bookmark.xml"
    eventlog_name: "Camstar"
    xpath_query: '*'
    labels:
      job: camstar
  relabel_configs:
    - source_labels: ['computer']
      target_label: 'host'
      
- job_name: system
  pipeline_stages:
  
  - output:
      source: message
      action_on_failure: skip
   
  static_configs:
  - targets:
      - localhost
    labels:
      job: iislogs
      agent: promtail
      __path__: c:/inetpub/logs/logfiles/*/*